version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build Project
          command: dotnet build --configuration Release

      - run:
          name: Run Tests
          command: dotnet test --configuration Release || true

      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud